### ISSUE TITLE
podAnnotations - did not find expected key

### ISSUE THREAD

**Issue by alanorther** [nsqio/helm-chart#10]
### Issue:
Adding podAnnotations value to nsqlookupd, nsqadmin, or nsqd in the values file gives the following error or similar:
helm upgrade --install -f nsq-values.yaml nsq nsqio/nsq
Error: UPGRADE FAILED: YAML parse error on nsq/templates/nsqadmin-deployment.yaml: error converting YAML to JSON: yaml: line 19: did not find expected key

### Example Values File Input:
```
  podAnnotations:
    Test_Annotations: "testing"
```

### Fix to template files:
```
    metadata:
      {{- with .Values.nsqlookupd.podAnnotations }}
+     annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

### Files that require update:
templates/nsqadmin-deployment.yaml
templates/nsqd-statefulset.yaml
templates/nsqlookupd-statefulset.yaml

**Comment by ploxiln** [comment]
Hmm, it's been that way from the first commit in this repo. Maybe no-one ever used `podAnnotations`. Though maybe you could theoretically do something like:

```yaml
podAnnotations:
  annotations:
    myrealm: blue
```

Anyway, would you like to open a Pull Request with your suggested fix?
