### ISSUE TITLE
Topic Creation through admin vs http post

### ISSUE THREAD

**Issue by Arvindh-Mojo** [nsqio/helm-chart#11]
Hey.. is there some sort of known issue with this scenario. 

i have the nsq suite running in my eks environment. Through the admin portal, if i create a topic and go to the topic, i get an upstream error however if i use the http post method to create topic, it works fine. 

While this is not a big deal, was wondering if there is any known issue or this is some of configuration problem.

**Comment by mreiferson** [comment]
Can you provide `nsqadmin` logs?
