### ISSUE TITLE
nsqadmin-deployment.yaml tolerations vaules and etc 

### ISSUE THREAD

**Issue by vavilenski** [nsqio/helm-chart#4]
Hello.

[Here](https://github.com/nsqio/helm-chart/blob/master/charts/nsq/templates/nsqadmin-deployment.yaml#L57)  wrong values secetor (right now - .Values.nodeSelector, need - .Values.nsqadmin.nodeSelector).

I will fix it.

**Comment by mreiferson** [comment]
fixed in #5
